name: CI-CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  pipeline:
    runs-on: ubuntu-latest
    env:
      PYTHONNOUSERSITE: "1"
    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Configure AWS creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubActionsDVCAndEKSRole
          aws-region: us-east-1

      - name: Install dependencies
        run: |
          python -m venv .venv
          .venv/bin/python -m pip install --upgrade pip setuptools wheel
          .venv/bin/python -m pip install --upgrade --force-reinstall -r requirements.txt

      - name: Debug Python package resolution
        run: |
          .venv/bin/python -c "import sys, pathspec; print(sys.executable); print(pathspec.__version__); print(pathspec.__file__); print('\\n'.join(sys.path))"
          .venv/bin/python -m pip show dvc pathspec

      - name: Pull data and model
        run: |
          .venv/bin/python -m dvc pull

      - name: Login DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: jbquirk/ml-api:${{ github.sha }}

      - name: Update manifest image tag
        run: |
          sed -i "s#image: .*#image: docker-username/ml-api:${GITHUB_SHA}#g" k8s/manifest.yaml
      - name: Commit changes
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add k8s/manifest.yaml
          git commit -m "Update image tag"
          git push
